export const BSW = {
  domain:"bswhealth.com", title:"Baylor Scott & White Health",
  industry:"Healthcare System · Texas", crawledAt:"June 15, 2026 · 14:32 UTC",
  summary:"Texas's largest not-for-profit healthcare system — hospitals, clinics, physician offices and virtual care. Every provider profile, location listing and specialty page is hydrated at load time from third-party APIs (Epic, Phynd, Google Maps) inside a Sitecore XM Cloud headless CMS.",
  tags:["healthcare","hospital network","telehealth","patient portal","multi-location","not-for-profit","HIPAA"],
  tech:["Sitecore XM Cloud","Next.js Headless","Epic / MyChart","Google Tag Manager","Azure Blob CDN","Google Maps Places API","Phynd NPI"],
  metrics:{pages:12000,sections:11,templates:5,apis:4,crawlTime:"3.2s"},
  nodes:[
    {id:"home",label:"Home",parent:null,count:1},{id:"physicians",label:"Physicians",parent:"home",count:4200},
    {id:"allied",label:"Allied Health",parent:"home",count:1800},{id:"locations",label:"Locations",parent:"home",count:744},
    {id:"blog",label:"Blog / News",parent:"home",count:2200},{id:"specialties",label:"Specialties",parent:"home",count:180},
    {id:"np",label:"Nurse Practitioners",parent:"physicians",count:900},{id:"pa",label:"Physician Asst",parent:"physicians",count:600},
    {id:"therapists",label:"Therapists",parent:"allied",count:120},{id:"dieticians",label:"Dieticians",parent:"allied",count:80},
    {id:"audiologists",label:"Audiologists",parent:"allied",count:40},{id:"clinics",label:"Clinics",parent:"locations",count:500},
    {id:"hospitals",label:"Hospitals",parent:"locations",count:52},{id:"virtual",label:"Virtual Care",parent:"specialties",count:12},
  ],
  templates:[
    {id:"tp1",name:"Physician / Provider Profile",count:7500,total:12000,pattern:"/physician/* · /nurse-practitioner/*",color:"#6366F1",
      features:["Photo & bio","Specialties & languages","Insurance list","Epic scheduling widget","Real-time availability","Distance from user"],apis:["Phynd","Epic"],
      layers:[
        {label:"Nav bar (static CMS)",h:48,color:"#334155",api:null},
        {label:"Hero — name, photo, credentials",h:96,color:"#6366F1",api:"Phynd Provider API"},
        {label:"Bio + specialties + languages",h:72,color:"#6366F1",api:"Phynd Provider API"},
        {label:"Open scheduling widget (real-time slots)",h:88,color:"#10B981",api:"Epic Open Scheduling"},
        {label:"Insurance accepted",h:52,color:"#6366F1",api:"Phynd Provider API"},
        {label:"Location map",h:64,color:"#22D3EE",api:"Google Maps Places"},
        {label:"Footer (static CMS)",h:40,color:"#334155",api:null},
      ]},
    {id:"tp2",name:"Doctor Search / Filter",count:80,total:12000,pattern:"/doctors/{specialty}?distance=&sortBy=&keyword=",color:"#8B5CF6",
      features:["Geo-filtered results","Specialty filter","Sort by availability","Phynd/NPI data"],apis:["Phynd"],
      layers:[
        {label:"Nav bar (static CMS)",h:48,color:"#334155",api:null},
        {label:"Specialty heading + breadcrumb",h:52,color:"#334155",api:null},
        {label:"Provider result cards",h:140,color:"#6366F1",api:"Phynd Provider API"},
        {label:"Filter sidebar — distance, availability",h:88,color:"#6366F1",api:"Phynd Provider API"},
        {label:"Pagination / load more",h:36,color:"#334155",api:null},
        {label:"Footer (static CMS)",h:40,color:"#334155",api:null},
      ]},
    {id:"tp3",name:"Location / Clinic Finder",count:744,total:12000,pattern:"/locations/clinic · /locations/hospital",color:"#22D3EE",
      features:["Google Maps pins","Hours & walk-in","Services offered","Azure photo CDN"],apis:["Geo API","Google Maps"],
      layers:[
        {label:"Nav bar (static CMS)",h:48,color:"#334155",api:null},
        {label:"Search + geo filter bar",h:56,color:"#22D3EE",api:"Location Geo API"},
        {label:"744 clinic cards (Azure photos)",h:128,color:"#22D3EE",api:"Location Geo API"},
        {label:"Google Maps pin map",h:110,color:"#22D3EE",api:"Google Maps Places"},
        {label:"Hours & walk-in status",h:48,color:"#22D3EE",api:"Location Geo API"},
        {label:"Footer (static CMS)",h:40,color:"#334155",api:null},
      ]},
    {id:"tp4",name:"Blog / Health Article",count:2200,total:12000,pattern:"/news/* · /blog/* · /resources/*",color:"#F59E0B",
      features:["Author attribution","Category tags","Related articles","SEO meta"],apis:[],
      layers:[
        {label:"Nav bar (static CMS)",h:48,color:"#334155",api:null},
        {label:"Hero image + title",h:100,color:"#F59E0B",api:null},
        {label:"Article body (CMS rich text)",h:180,color:"#334155",api:null},
        {label:"Author card + tags",h:52,color:"#F59E0B",api:null},
        {label:"Related articles widget",h:72,color:"#334155",api:null},
        {label:"Footer (static CMS)",h:40,color:"#334155",api:null},
      ]},
    {id:"tp5",name:"Specialty / Service Page",count:180,total:12000,pattern:"/specialties/* · /treatments-and-procedures/*",color:"#10B981",
      features:["Condition overview","Find a Doctor CTA","Related locations"],apis:["Phynd"],
      layers:[
        {label:"Nav bar (static CMS)",h:48,color:"#334155",api:null},
        {label:"Specialty hero (CMS)",h:80,color:"#10B981",api:null},
        {label:"Condition overview (CMS)",h:100,color:"#334155",api:null},
        {label:"Find a Doctor CTA → Phynd query",h:60,color:"#6366F1",api:"Phynd Provider API"},
        {label:"Related locations",h:56,color:"#22D3EE",api:"Location Geo API"},
        {label:"Footer (static CMS)",h:40,color:"#334155",api:null},
      ]},
  ],
  apis:[
    {name:"Phynd Provider Directory API",type:"Healthcare · Provider Data",confidence:"High",color:"#6366F1",
      endpoints:["/physician/{slug}","/doctors/{specialty}?distance=&sortBy=&keyword="],
      purpose:"Serves all provider profile data — NPI numbers, specialties, languages, insurance accepted, photo, bio, geo-distance.",
      method:"REST / JSON — headless CMS hydration at edge",trigger:"Page load · filter/sort · specialty search"},
    {name:"Epic Open Scheduling API",type:"Booking · EHR Integration",confidence:"High",color:"#10B981",
      endpoints:["openSchedule JSON in /physician/* page meta","visitTypeId · departmentId · providerEpicId"],
      purpose:"Returns real-time appointment slot availability by provider, visit type and department. Pre-fetched into page meta on load.",
      method:"Epic FHIR / proprietary JSON",trigger:"Page load → Schedule button"},
    {name:"Location Search & Geo API",type:"Geolocation · Facility Data",confidence:"High",color:"#22D3EE",
      endpoints:["/locations/clinic · /locations/hospital","Google Maps place_id","bswmedia.blob.core.windows.net"],
      purpose:"Loads 744+ clinic records geo-filtered by user location with walk-in status, hours, and map pins.",
      method:"REST + Google Maps Places + Azure Blob CDN",trigger:"Page load · geo-permission · filter"},
    {name:"Google Tag Manager (first-party)",type:"Analytics · Tag Management",confidence:"High",color:"#F59E0B",
      endpoints:["gtm.bswhealth.com (GTM-PGCTTH)","gtm_auth token"],
      purpose:"Manages all tracking — GA4, pixels, A/B tests, chat widgets. Custom subdomain for first-party data strategy.",
      method:"JS tag injection via GTM container",trigger:"Every page load + interaction events"},
  ],
  projects:[
    {id:1,name:"bswhealth.com",pages:12000,status:"done",date:"Today, 14:32",score:94},
    {id:2,name:"crystalgolfresort.com",pages:312,status:"done",date:"Yesterday",score:78},
    {id:3,name:"mybswhealth.com",pages:840,status:"queued",date:"Queued",score:null},
  ],
};
